if accepted this commit will complete ncnews7
Paulos-se/nc-news pull request #6
Opened 2022-07-26 15:37 UTC by Paulos-se

2022-07-26 15:40 UTC, Angaca requested changes
It works very smoothly and I really like it, the only change you need is that you should allow the user to only like/dislike once and only if I change my mind and remove that vote re like/dislike

2022-07-27 08:20 UTC, Angaca requested changes
Still some changes are needed, now I can correctly only vote once but I cannot change my mind, remove my casted vote and re-do it if I like. Plus is not a nice user experience that the button is clickable but does nothing. 
What should happen is having the button press and you increment, re press the button to remove it but then I should be able to press it again, the opposite button should be disabled while my vote is casted and reactivated when I remove my vote

2022-07-27 10:42 UTC, HeatherEver reviewed
Looks good but I would maybe add once more piece of functionality - when the like button is pressed and the like goes up - if we press the like button again to 'deselect' it i would be nice if the votes went down. 
This features can just be added into the if (liked) statement at the top of your functions to take away that vote
same for voting down please - then it's complete!

2022-07-27 11:58 UTC, Angaca requested changes
Love it visually, there is a bug to fix, if I keep changing them the website crash :(

2022-07-27 13:54 UTC, douglashellowell commented on src/components/UpdateVote.jsx
> +  const [unLikeDisable, unLikeSetDisable] = useState(false);
these booleans seem to be changing at the same time to the same value - how is `liked` and `likeDisable` different?

2022-07-27 13:56 UTC, douglashellowell commented on src/components/UpdateVote.jsx
> +
a lot of repeated code here - try to keep your code DRY

If the differences in these functions is `+1` or `-1` then consider passing it in as a variable and having one function that handles both

2022-07-27 14:02 UTC, douglashellowell commented
[link to code](https://github.dev/Paulos-se/nc-news/blob/91bbd0d7210352226f867b6e28a05b05b931010e/src/components/SingleArticle.jsx#L29-L30)
I'm not sure if you want to include `isLoading` in the dependancy array here
You only want to fetch the article again if the `article_id` changes!

2022-07-27 14:06 UTC, douglashellowell commented
There's some inconsistancy in how your buttons look when they are clickable or disabled - see video

https://user-images.githubusercontent.com/53038423/181267896-568eb98c-4b32-4a69-a58b-7d476eb8c384.mov

2022-07-27 14:10 UTC, douglashellowell commented
Final bit of feedback from me:

At the moment you are rendering the votes on the page but they look like just a random number!

put a symbol or some text near the number to indicate what it represents

2022-07-27 15:24 UTC, douglashellowell commented
CSS on those buttons is much better 🙌

The code should still be tidied up here - you don't need both your `upVote` and `downVote` functions

after that it's ready to merge! 🚀

2022-07-28 10:28 UTC, merged